### ISSUE TITLE
full-heal resurrection issues

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#395]
In its current form, full-heal does not seem to add dead units back to the civilization, so resurrected units won't be able to join the military or hold office. I haven't tested it so it may or may not be an issue.

**Comment by cdombroski** [comment]
I fixed an error with unit selection in this script, but didn't see any issues with resurrected units. Has anybody else verified this?

**Comment by lethosor** [comment]
In 0.44.05, I used `exterminate` to kill dwarves both with and without noble positions, then resurrected them with `full-heal -r`, and they still appear on the `n`obles screen in both cases. Unless I'm misunderstanding the original issue, I think it's working now.
